name: al_dahabiya
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  animation_search_bar: ^0.0.10
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  drop_down_list: ^0.0.8
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  get_it: ^7.6.4
  go_router: ^14.2.7
  jwt_decoder: ^2.0.1
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo-removebg-preview.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  #
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
